using System.Linq;
using AspNetMembershipManager.Web;

namespace AspNetMembershipManager.User
{
    class CreateUserModel : SaveViewModelBase
    {
    	private readonly IMembershipSettings membershipSettings;

    	public CreateUserModel(IMembershipSettings membershipSettings)
    	{
    		this.membershipSettings = membershipSettings;
			IsManualPasswordEntry = true;
    	}

    	public string Username { get; set; }

		public string EmailAddress { get; set; }

		private string password;
		public string Password
		{
			get { return password; }
			set
			{
				password = value;
				OnPropertyChanged("password");
				OnPropertyChanged("PasswordConfirmation");
			}
		}
		public string PasswordConfirmation { get; set; }

		public bool IsPasswordAutoGenerated { get; private set; }

		public bool IsManualPasswordEntry { get; private set; }

    	public bool RequiresQuestionAndAnswer
    	{
    		get { return membershipSettings.RequiresQuestionAndAnswer; }
    	}

    	public string PasswordQuestion { get; set; }

    	public string PasswordQuestionAnswer { get; set; }

    	public override string this[string columnName]
    	{
    		get
    		{
    			switch (columnName)
    			{
                    case "UserName":
                        if (string.IsNullOrEmpty(Username))
						{
							return "Please enter a unique username";
						}
						break;
					case "Password":
                        if (! ValidatePassword(Password))
						{
							return "Password does not meet the length or complexity requirements";
						}
						break;
					case "PasswordConfirmation":
                        if (Password != PasswordConfirmation)
						{
							return "Passwords do not match";
						}
						break;
    			}
    			return string.Empty;
    		}
    	}

		private bool ValidatePassword(string password)
		{
            if (string.IsNullOrEmpty(password) || password.Length < membershipSettings.MinRequiredPasswordLength)
			{
				return false;
			}
		    return membershipSettings.MinRequiredNonAlphanumericCharacters <= password.Count(c => ! char.IsLetterOrDigit(c));
		}

    	public void SetAutoGenerateneratedPassword(string password)
		{
			Password = password;
			PasswordConfirmation = password;
			IsPasswordAutoGenerated = true;
			IsManualPasswordEntry = false;

			OnPropertyChanged("Password");
			OnPropertyChanged("PasswordConfirmation");
			OnPropertyChanged("IsPasswordAutoGenerated");
			OnPropertyChanged("IsManualPasswordEntry");
		}
    }
}